### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by KaiQiao1992** [ivclab/BigGAN-Generator-Pretrained-Pytorch#1]
How are the pretrained weights converted from the tensorflow hub modules?

**Comment by Jia-HongHenryLee** [comment]
@andrewhsiehth has question.~~~~~

**Comment by ifndef012** [comment]
@KaiQiao1992 
I manually inspected the computational graph in the tensorflow hub modules, and looked for every corresponding operator in pytorch to apply on their pre-trained weights.

**Comment by KaiQiao1992** [comment]
got it and thank you for your response.

andrewhsiehth <notifications@github.com> 于2020年3月27日周五 上午12:42写道：
